# Generated by Django 3.2.9 on 2021-12-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211208_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermicky',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermicky',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermicky',
            name='user_permissions',
        ),
    ]
